# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: I am a UX Designer who loves creating accessible products.
titlenodes:
- text: simplicity
- text: accessibility
- text: technology
- text: ethics
- text: patterns
email: contact@danoc.nl
description: >- # this means to ignore newlines until "baseurl:"
  Dan O'Connell - I am a UX Designer who loves creating accessible products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/portfolio-jekyll" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  theorise

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed
  sass_dir: css

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
